app:
    port: "8082"
log:
    env: "dev"
gateway:
    paymentservice:
        hosturl: "http://18.206.181.139:3101"
    menuservice:
        hosturl: "http://18.206.181.139:3102"
awssession:
    id: AWS_ID
    secret: AWS_SECRET